"""empty message

Revision ID: 0837186af362
Revises: 
Create Date: 2025-01-19 17:30:38.255125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0837186af362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='项目名称'),
    sa.Column('describe', sa.Text(), nullable=True, comment='对项目进行描述'),
    sa.Column('status', sa.Integer(), nullable=False, comment='项目状态， 未开始、进行中、已结束'),
    sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目组id'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='任务名称'),
    sa.Column('describe', sa.Text(), nullable=True, comment='对任务进行描述'),
    sa.Column('status', sa.Integer(), nullable=False, comment='任务状态， 未开始、进行中、已结束'),
    sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目id'),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='任务id'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='用户名'),
    sa.Column('role', sa.Integer(), nullable=True, comment='用户角色，管理员、访客 默认：访客'),
    sa.Column('status', sa.Integer(), nullable=False, comment='用户状态，未启用、活跃、注销, 默认未启动'),
    sa.Column('expand', sa.Text(), nullable=True, comment='扩展参数'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('project')
    # ### end Alembic commands ###
